[project]
name = "gemini-engineer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-genai>=0.3.0",
    "nicegui>=2.9.0",
    "python-dotenv>=1.0.1",
    "scipy>=1.14.1",
    "sounddevice>=0.5.1",
]